packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: false
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
